# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_py_libGBP', [dirname(__file__)])
        except ImportError:
            import _py_libGBP
            return _py_libGBP
        if fp is not None:
            try:
                _mod = imp.load_module('_py_libGBP', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _py_libGBP = swig_import_helper()
    del swig_import_helper
else:
    import _py_libGBP
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class GaussianBeam(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GaussianBeam, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GaussianBeam, name)
    __repr__ = _swig_repr
    def getFrequency(self): return _py_libGBP.GaussianBeam_getFrequency(self)
    def getWavelength(self): return _py_libGBP.GaussianBeam_getWavelength(self)
    def getWaistPosition(self): return _py_libGBP.GaussianBeam_getWaistPosition(self)
    def getWaistDiameter(self): return _py_libGBP.GaussianBeam_getWaistDiameter(self)
    def getPower(self): return _py_libGBP.GaussianBeam_getPower(self)
    def getCurrentPosition(self): return _py_libGBP.GaussianBeam_getCurrentPosition(self)
    def getFreeSpaceWavelength(self): return _py_libGBP.GaussianBeam_getFreeSpaceWavelength(self)
    def getRayleighRange(self): return _py_libGBP.GaussianBeam_getRayleighRange(self)
    def getDivergence(self): return _py_libGBP.GaussianBeam_getDivergence(self)
    def getDiameter(self): return _py_libGBP.GaussianBeam_getDiameter(self)
    def getRadius(self): return _py_libGBP.GaussianBeam_getRadius(self)
    def getWaistRadius(self): return _py_libGBP.GaussianBeam_getWaistRadius(self)
    def getRadiusOfCurvature(self): return _py_libGBP.GaussianBeam_getRadiusOfCurvature(self)
    def getComplexBeamParameter(self): return _py_libGBP.GaussianBeam_getComplexBeamParameter(self)
    def getRelativeWaistPosition(self): return _py_libGBP.GaussianBeam_getRelativeWaistPosition(self)
    def getArea(self): return _py_libGBP.GaussianBeam_getArea(self)
    def getPeakIrradiance(self): return _py_libGBP.GaussianBeam_getPeakIrradiance(self)
    def __init__(self): 
        this = _py_libGBP.new_GaussianBeam()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _py_libGBP.delete_GaussianBeam
    __del__ = lambda self : None;
GaussianBeam_swigregister = _py_libGBP.GaussianBeam_swigregister
GaussianBeam_swigregister(GaussianBeam)

# This file is compatible with both classic and new-style classes.


