# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_py_libGBP')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_py_libGBP')
    _py_libGBP = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_py_libGBP', [dirname(__file__)])
        except ImportError:
            import _py_libGBP
            return _py_libGBP
        if fp is not None:
            try:
                _mod = imp.load_module('_py_libGBP', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _py_libGBP = swig_import_helper()
    del swig_import_helper
else:
    import _py_libGBP
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


import pint
ureg = pint.UnitRegistry()
Q_   = ureg.Quantity

class GaussianBeam(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GaussianBeam, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GaussianBeam, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _py_libGBP.delete_GaussianBeam
    __del__ = lambda self: None
GaussianBeam_swigregister = _py_libGBP.GaussianBeam_swigregister
GaussianBeam_swigregister(GaussianBeam)


@ureg.wraps( None, (None,ureg('hertz')), True )
def setFrequency (self,v):
  return self.setFrequencyDP(v)
GaussianBeam.setFrequency  = setFrequency 


@ureg.wraps( ureg('hertz'), None, True )
def getFrequency (self):
  return self.getFrequencyDP()
GaussianBeam.getFrequency = getFrequency 


@ureg.wraps( None, (None,ureg('nanometer')), True )
def setWavelength (self,v):
  return self.setWavelengthDP(v)
GaussianBeam.setWavelength  = setWavelength 


@ureg.wraps( ureg('nanometer'), None, True )
def getWavelength (self):
  return self.getWavelengthDP()
GaussianBeam.getWavelength = getWavelength 


@ureg.wraps( None, (None,ureg('centimeter')), True )
def setWaistPosition (self,v):
  return self.setWaistPositionDP(v)
GaussianBeam.setWaistPosition  = setWaistPosition 


@ureg.wraps( ureg('centimeter'), None, True )
def getWaistPosition (self):
  return self.getWaistPositionDP()
GaussianBeam.getWaistPosition = getWaistPosition 


@ureg.wraps( None, (None,ureg('centimeter')), True )
def setWaistDiameter (self,v):
  return self.setWaistDiameterDP(v)
GaussianBeam.setWaistDiameter  = setWaistDiameter 


@ureg.wraps( ureg('centimeter'), None, True )
def getWaistDiameter (self):
  return self.getWaistDiameterDP()
GaussianBeam.getWaistDiameter = getWaistDiameter 


@ureg.wraps( None, (None,ureg('watt')), True )
def setPower (self,v):
  return self.setPowerDP(v)
GaussianBeam.setPower  = setPower 


@ureg.wraps( ureg('watt'), None, True )
def getPower (self):
  return self.getPowerDP()
GaussianBeam.getPower = getPower 


@ureg.wraps( None, (None,ureg('centimeter')), True )
def setCurrentPosition (self,v):
  return self.setCurrentPositionDP(v)
GaussianBeam.setCurrentPosition  = setCurrentPosition 


@ureg.wraps( ureg('centimeter'), None, True )
def getCurrentPosition (self):
  return self.getCurrentPositionDP()
GaussianBeam.getCurrentPosition = getCurrentPosition 


@ureg.wraps( ureg('nanometer'), None, True )
def getFreeSpaceWavelength (self):
  return self.getFreeSpaceWavelengthDP()
GaussianBeam.getFreeSpaceWavelength = getFreeSpaceWavelength 


@ureg.wraps( ureg('centimeter'), None, True )
def getRayleighRange (self):
  return self.getRayleighRangeDP()
GaussianBeam.getRayleighRange = getRayleighRange 


@ureg.wraps( None, (None,ureg('centimeter')), True )
def setFocalLength (self,v):
  return self.setFocalLengthDP(v)
ThinLens.setFocalLength  = setFocalLength 


@ureg.wraps( ureg('centimeter'), None, True )
def getFocalLength (self):
  return self.getFocalLengthDP()
ThinLens.getFocalLength = getFocalLength 

# This file is compatible with both classic and new-style classes.


